// Stupid Text Code

pub enum STCValue {
    // 0 1 2 3 4 5 6 7 8 9
    Zero,
    One,
    Two,
    Three,
    Four,
    Five,
    Six,
    Seven,
    Eight,
    Nine,

    // A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
    UppercaseA,
    UppercaseB,
    UppercaseC,
    UppercaseD,
    UppercaseE,
    UppercaseF,
    UppercaseG,
    UppercaseH,
    UppercaseI,
    UppercaseJ,
    UppercaseK,
    UppercaseL,
    UppercaseM,
    UppercaseN,
    UppercaseO,
    UppercaseP,
    UppercaseQ,
    UppercaseR,
    UppercaseS,
    UppercaseT,
    UppercaseU,
    UppercaseV,
    UppercaseW,
    UppercaseX,
    UppercaseY,
    UppercaseZ,

    // a b c d e f g h i j k l m n o p q r s t u v w x y z
    LowercaseA,
    LowercaseB,
    LowercaseC,
    LowercaseD,
    LowercaseE,
    LowercaseF,
    LowercaseG,
    LowercaseH,
    LowercaseI,
    LowercaseJ,
    LowercaseK,
    LowercaseL,
    LowercaseM,
    LowercaseN,
    LowercaseO,
    LowercaseP,
    LowercaseQ,
    LowercaseR,
    LowercaseS,
    LowercaseT,
    LowercaseU,
    LowercaseV,
    LowercaseW,
    LowercaseX,
    LowercaseY,
    LowercaseZ,

    // ? ! . : ; , / + - * - _ #
    QuestionMark,
    ExclamationMark,
    Period,
    Colon,
    Semicolon,
    Comma,
    Slash,
    Plus,
    Minus,
    Asterisk,
    Dash,
    Underscore,
    Hashtag,

    // () [] <> {}
    ParenthesesRoundOpen,
    ParenthesesRoundClose,
    ParenthesesSquareOpen,
    ParenthesesSquareClose,
    ParenthesesPointyOpen,
    ParenthesesPointyClose,
    ParenthesesCurlyOpen,
    ParenthesesCurlyClose,

    // Invisible Characters
    Newline,
    Remove,
    Tab,
    Modifier0,
    Modifier1,
    Modifier2,
    Space,

    // Mode-setting command
    StandardOutput,
    StandardInput,
    Formatting,
    Data,
    // Reserve 6 more of them
}

impl STCValue {
    fn to_ascii(&self) -> Option<char> {
        match self {
            STCValue::Zero => Some('0'),
            STCValue::One => Some('1'),
            STCValue::Two => Some('2'),
            STCValue::Three => Some('3'),
            STCValue::Four => Some('4'),
            STCValue::Five => Some('5'),
            STCValue::Six => Some('6'),
            STCValue::Seven => Some('7'),
            STCValue::Eight => Some('8'),
            STCValue::Nine => Some('9'),
            STCValue::UppercaseA => Some('A'),
            STCValue::UppercaseB => Some('B'),
            STCValue::UppercaseC => Some('C'),
            STCValue::UppercaseD => Some('D'),
            STCValue::UppercaseE => Some('E'),
            STCValue::UppercaseF => Some('F'),
            STCValue::UppercaseG => Some('G'),
            STCValue::UppercaseH => Some('H'),
            STCValue::UppercaseI => Some('I'),
            STCValue::UppercaseJ => Some('J'),
            STCValue::UppercaseK => Some('K'),
            STCValue::UppercaseL => Some('L'),
            STCValue::UppercaseM => Some('M'),
            STCValue::UppercaseN => Some('N'),
            STCValue::UppercaseO => Some('O'),
            STCValue::UppercaseP => Some('P'),
            STCValue::UppercaseQ => Some('Q'),
            STCValue::UppercaseR => Some('R'),
            STCValue::UppercaseS => Some('S'),
            STCValue::UppercaseT => Some('T'),
            STCValue::UppercaseU => Some('U'),
            STCValue::UppercaseV => Some('V'),
            STCValue::UppercaseW => Some('W'),
            STCValue::UppercaseX => Some('X'),
            STCValue::UppercaseY => Some('Y'),
            STCValue::UppercaseZ => Some('Z'),
            STCValue::LowercaseA => Some('a'),
            STCValue::LowercaseB => Some('b'),
            STCValue::LowercaseC => Some('c'),
            STCValue::LowercaseD => Some('d'),
            STCValue::LowercaseE => Some('e'),
            STCValue::LowercaseF => Some('f'),
            STCValue::LowercaseG => Some('g'),
            STCValue::LowercaseH => Some('h'),
            STCValue::LowercaseI => Some('i'),
            STCValue::LowercaseJ => Some('j'),
            STCValue::LowercaseK => Some('k'),
            STCValue::LowercaseL => Some('l'),
            STCValue::LowercaseM => Some('m'),
            STCValue::LowercaseN => Some('n'),
            STCValue::LowercaseO => Some('o'),
            STCValue::LowercaseP => Some('p'),
            STCValue::LowercaseQ => Some('q'),
            STCValue::LowercaseR => Some('r'),
            STCValue::LowercaseS => Some('s'),
            STCValue::LowercaseT => Some('t'),
            STCValue::LowercaseU => Some('u'),
            STCValue::LowercaseV => Some('v'),
            STCValue::LowercaseW => Some('w'),
            STCValue::LowercaseX => Some('x'),
            STCValue::LowercaseY => Some('y'),
            STCValue::LowercaseZ => Some('z'),

            STCValue::QuestionMark => Some('?'),
            STCValue::ExclamationMark => Some('!'),
            STCValue::Period => Some('.'),
            STCValue::Colon => Some(':'),
            STCValue::Semicolon => Some(';'),
            STCValue::Comma => Some(','),
            STCValue::Slash => Some('/'),
            STCValue::Plus => Some('+'),
            STCValue::Minus => Some('-'),
            STCValue::Asterisk => Some('*'),
            STCValue::Dash => Some('-'),
            STCValue::Underscore => Some('_'),
            STCValue::Hashtag => Some('#'),

            STCValue::ParenthesesRoundOpen => Some('('),
            STCValue::ParenthesesRoundClose => Some(')'),
            STCValue::ParenthesesSquareOpen => Some('['),
            STCValue::ParenthesesSquareClose => Some(']'),
            STCValue::ParenthesesPointyOpen => Some('<'),
            STCValue::ParenthesesPointyClose => Some('>'),
            STCValue::ParenthesesCurlyOpen => Some('{'),
            STCValue::ParenthesesCurlyClose => Some('}'),

            STCValue::Newline => Some('\n'),
            STCValue::Tab => Some('\t'),
            STCValue::Space => Some(' '),

            _ => None,
        }
    }
}

